### ISSUE TITLE
Test for the error handling logic in CDCLogReader

### ISSUE THREAD

**Issue by piodul** [piodul/scylla-cdc-rust#100]
Based on the recent benchmarks, there is a reason to believe that there is a bug in the error handling logic in the CDCLogReader. It needs to be debugged and test(s) should be added which verify that it works.

**Comment by procrastinationfighter** [comment]
What is the expected behavior here? If I remember correctly, the problem was that when a tokio task returned an error, the library was still working (and would not stop, because the error was most likely not propagated in the correct way). So I guess that we just want `CDCLogReader` to stop and return the error?

**Comment by piodul** [comment]
Yes. More specifically, I'm interested in the case where the CDCConsumer returns an error - if that happens then the library should be stopped.

There is another case where the query done by stream reader returns an error. This was probably what happened in our benchmarks, but it should probably handled differently - I'm still thinking about it (retried, probably).

**Comment by procrastinationfighter** [comment]
Apparently, the bug was in the benchmark application - the main process was waiting for a signal after all rows have been read - and if some error occurred, then the signal was never sent. 

The lines of code I'm referring to: https://github.com/procrastinationfighter/scylla-cdc-rust-benchmark/blob/4e0eef428fbc0b6efde91186a5345eeaf4337238/rust-reader/src/main.rs#L81-L89

**Comment by piodul** [comment]
> Apparently, the bug was in the benchmark application - the main process was waiting for a signal after all rows have been read - and if some error occurred, then the signal was never sent.
> 
> The lines of code I'm referring to: https://github.com/procrastinationfighter/scylla-cdc-rust-benchmark/blob/4e0eef428fbc0b6efde91186a5345eeaf4337238/rust-reader/src/main.rs#L81-L89

Indeed it looks like it, thanks. Let's add a test for it anyway - even if the error handling logic in CDCLogReader is correct, adding a test will reduce a chance of introducing a real bug there in the future.
