### ISSUE TITLE
Replicator: Precompute queries

### ISSUE THREAD

**Issue by procrastinationfighter** [piodul/scylla-cdc-rust#33]
The replicator creates some queries dynamically ([example](https://github.com/piodul/scylla-cdc-rust/pull/28#discussion_r782377259)). These queries should be precomputed.

**Comment by piodul** [comment]
One small implementation note: currently, a single `session.query()` in the replicator will not always translate to a single prepared statement. A dynamic query will usually depend on some finite set of parameters (e.g. a column name), therefore instead of a single prepared statement we should probably keep a map of type `parameters -> prepared statement`. The map can be either initialized at the start of the replicator or its entries can be initialized lazily, whichever is easier.
